[mosquitoes.generation]
interval_between_female_postures = { min = 1.000, max = 1.000 }
female_gestation_cycles = { min = 3.000, max = 8.000 }
healthy_offspring_transition_active_to_egg = { min = 4.000, max = 8.000 }
fraction_healthy_male_offspring_active_to_egg = { min = 0.500, max = 0.500 }
fraction_female_egg_laying_declining_healthy = { min = 0.700, max = 0.700 }
fraction_healthy_male_offspring_declining_to_egg = { min = 0.500, max = 0.500 }
infected_offspring_transition_active_to_egg = { min = 4.000, max = 8.000 }
fraction_infected_male_offspring_active_to_egg = { min = 0.500, max = 0.500 }
fraction_female_egg_laying_declining_infected = { min = 0.700, max = 0.700 }
fraction_infected_male_offspring_declining_to_egg = { min = 0.500, max = 0.500 }
limit_agents_aquatic_phase_per_focus = { min = 10.000, max = 10.000 }
