[mosquitos.control]
natural_control_frequency_cycles = { min = 1.0, max = 1.0 }

natural_control_selection_male_eggs_without_wolbachia_percentage = { min = 0.085, max = 0.087 }
natural_control_selection_male_eggs_with_wolbachia_percentage = { min = 0.085, max = 0.087 }
natural_control_selection_female_eggs_without_wolbachia_percentage = { min = 0.085, max = 0.087 }
natural_control_selection_female_eggs_with_wolbachia_percentage = { min = 0.085, max = 0.087 }
natural_control_selection_male_larvae_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_male_larvae_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_female_larvae_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_female_larvae_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_male_pupae_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_male_pupae_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_female_pupae_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_female_pupae_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_active_males_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_active_males_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_active_females_without_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }
natural_control_selection_active_females_with_wolbachia_percentage = { min = 0.055999999999999994, max = 0.057999999999999996 }

biological_control_frequency_cycles = { min = 0.0, max = 0.0 }
biological_control_active_males_with_wolbachia_quantity = { min = 0.0, max = 0.0 }
biological_control_active_females_with_wolbachia_quantity = { min = 0.0, max = 0.0 }

environmental_treatment_frequency_cycles = { min = 0.0, max = 0.0 }
mosquitoes_affected_by_environmental_treatment_fraction = { min = 0.4, max = 0.6 }
influence_type_draw_rate = { min = 0.1, max = 0.2 }
chemical_controls_decay = { min = 0.016669999999999997, max = 0.016669999999999997 }

aquatic_phase_mosquitoes_control_multiplier_very_high = { min = 0.60, max = 0.65 }
aquatic_phase_mosquitoes_control_multiplier_high = { min = 0.60, max = 0.65 }
aquatic_phase_mosquitoes_control_multiplier_regular = { min = 0.60, max = 0.65 }
aquatic_phase_mosquitoes_control_multiplier_low = { min = 0.60, max = 0.65 }
aquatic_phase_mosquitoes_control_multiplier_very_low = { min = 0.60, max = 0.65 }
