[mosquitos.contact]
healthy_active_female_and_healthy_active_male_prob = { min = 0.90, max = 0.99 }
healthy_active_female_and_healthy_decadent_male_prob = { min = 0.80, max = 0.90 }

infected_active_female_and_infected_active_male_prob = { min = 0.30, max = 0.60 }
infected_active_female_and_infected_decadent_male_prob = { min = 0.30, max = 0.60 }
infected_active_female_and_healthy_active_male_prob = { min = 0.30, max = 0.60 }
infected_active_female_and_healthy_decadent_male_prob = { min = 0.30, max = 0.60 }

healthy_active_female_and_infected_active_male_prob = { min = 0.30, max = 0.60 }
healthy_active_female_and_infected_decadent_male_prob = { min = 0.30, max = 0.60 }

preference_factor_for_healthy_decadent_males = { min = 0.70, max = 0.80 }
preference_factor_for_infected_decadent_males = { min = 0.50, max = 0.50 }

female_fecundity_rate = { min = 0.90, max = 0.99 }
nighttime_reduction_in_mosquito_contact = { min = 0.1, max = 0.2 }
