[mosquitos.initialization]
distribution = [
  { gender = "m", phase = "a", state = "s", serotype = 1, quantity = { min = 240, max = 540 } },
  { gender = "m", phase = "a", state = "s", serotype = 1, quantity = { min = 240, max = 540 } },
  { gender = "m", phase = "e", state = "s", serotype = 1, quantity = { min = 240, max = 540 } },
]
random_distribution_probability = { min = 0.1, max = 0.2 }
