[mosquitos.movement]
daytime_mobility_rate_male_mosquito = { min = 0.99, max = 0.99 }
daytime_mobility_rate_female_mosquito = { min = 0.99, max = 0.99 }
nighttime_mobility_rate_male_mosquito = { min = 0.05, max = 0.15 }
nighttime_mobility_rate_female_mosquito = { min = 0.05, max = 0.15 }
female_search_radius_for_male = { min = 36, max = 36 }
search_radius_for_strategic_point = { min = 36, max = 36 }
interval_between_egg_laying_attempts = { min = 3, max = 3 }
human_search_radius = { min = 36, max = 36 }
short_levy_flight_displacements = { min = 4, max = 4 }
long_levy_flight_displacements = { min = 8, max = 8 }
attempts_to_find_male = { min = 3, max = 3 }
attempts_to_find_strategic_point = { min = 3, max = 3 }
mobility_rate_for_mosquito_with_idle_type_influence = { min = 0.01, max = 0.10 }
