[humans.contact]
mosquito_infection_rate = { min = 0.60, max = 0.95 }
mosquito_infection_success_rate = { min = 1.00, max = 1.00 }

susceptible_human_infection_rate_baby = { min = 1.00, max = 1.00 }
susceptible_human_infection_rate_child = { min = 1.00, max = 1.00 }
susceptible_human_infection_rate_teen = { min = 1.00, max = 1.00 }
susceptible_human_infection_rate_young_adult = { min = 1.00, max = 1.00 }
susceptible_human_infection_rate_adult = { min = 1.00, max = 1.00 }
susceptible_human_infection_rate_elderly = { min = 1.00, max = 1.00 }

recovered_human_infection_rate_baby = { min = 1.00, max = 1.00 }
recovered_human_infection_rate_child = { min = 1.00, max = 1.00 }
recovered_human_infection_rate_teen = { min = 1.00, max = 1.00 }
recovered_human_infection_rate_young_adult = { min = 1.00, max = 1.00 }
recovered_human_infection_rate_adult = { min = 1.00, max = 1.00 }
recovered_human_infection_rate_elderly = { min = 1.00, max = 1.00 }

human_infection_success_rate = { min = 0.60, max = 0.95 }
feeding_rate = { min = 0.60, max = 0.95 }

human_to_mosquito_complement_constant = { min = 1.0, max = 1.0 }
mosquito_to_human_complement_constant = { min = 1.0, max = 1.0 }

nighttime_human_mosquito_contact_reduction = { min = 0.1, max = 0.2 }
necessary_feeding_amount_for_egg_laying = { min = 2, max = 2 }
