#!/bin/bash

# print the usage message
usage() {
    echo -e "Usage: $0 [target]" 1>&2
    exit 1
}

command_exists() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "I require the command $1 but it's not installed. Abort."
        exit 1
    fi
}

# deps
for i in "xmake"; do
    command_exists "$i"
done

# get the first argument as target or use default (test)
target=${1:-test}
# shift all arguments to the left (original $1 gets lost)
shift

# Forward all script arguments to xmake run
xmake watch -y -- bash -c "xmake b $target && xmake r -vv -w . -- $target $*"
