groups = [
  { quadra = "0000", lote = "CLR01", id_lote = 0, id_quadra = 0 },
  { quadra = "0000", lote = "CLR02", id_lote = 1, id_quadra = 0 },
  { quadra = "0000", lote = "L1036", id_lote = 2, id_quadra = 0 },
  { quadra = "0000", lote = "L1066", id_lote = 3, id_quadra = 0 },
  { quadra = "0000", lote = "L1080", id_lote = 4, id_quadra = 0 },
  { quadra = "0000", lote = "L1137", id_lote = 5, id_quadra = 0 },
  { quadra = "0000", lote = "L1229", id_lote = 6, id_quadra = 0 },
  { quadra = "0000", lote = "L1327", id_lote = 7, id_quadra = 0 },
  { quadra = "0000", lote = "L1404", id_lote = 8, id_quadra = 0 },
  { quadra = "0000", lote = "L1405", id_lote = 9, id_quadra = 0 },
  { quadra = "0000", lote = "L1408", id_lote = 10, id_quadra = 0 },
  { quadra = "0000", lote = "L1410", id_lote = 11, id_quadra = 0 },
  { quadra = "0000", lote = "L1412", id_lote = 12, id_quadra = 0 },
  { quadra = "0000", lote = "L1413", id_lote = 13, id_quadra = 0 },
  { quadra = "0000", lote = "L1414", id_lote = 14, id_quadra = 0 },
  { quadra = "0000", lote = "L1530", id_lote = 15, id_quadra = 0 },
  { quadra = "0000", lote = "L154", id_lote = 16, id_quadra = 0 },
  { quadra = "0000", lote = "L155", id_lote = 17, id_quadra = 0 },
  { quadra = "0000", lote = "L1652", id_lote = 18, id_quadra = 0 },
  { quadra = "0000", lote = "L1661", id_lote = 19, id_quadra = 0 },
  { quadra = "0000", lote = "L209", id_lote = 20, id_quadra = 0 },
  { quadra = "0000", lote = "L302", id_lote = 21, id_quadra = 0 },
  { quadra = "0000", lote = "L722", id_lote = 22, id_quadra = 0 },
  { quadra = "0000", lote = "L849", id_lote = 23, id_quadra = 0 },
  { quadra = "0000", lote = "L851", id_lote = 24, id_quadra = 0 },
  { quadra = "0000", lote = "L852", id_lote = 25, id_quadra = 0 },
  { quadra = "0000", lote = "L853", id_lote = 26, id_quadra = 0 },
  { quadra = "0000", lote = "L98", id_lote = 27, id_quadra = 0 },
  { quadra = "Q34", lote = "L3159", id_lote = 0, id_quadra = 1 },
  { quadra = "Q34", lote = "L3170", id_lote = 1, id_quadra = 1 },
  { quadra = "Q34", lote = "L3171", id_lote = 2, id_quadra = 1 },
  { quadra = "Q34", lote = "L3189", id_lote = 3, id_quadra = 1 },
  { quadra = "Q34", lote = "L3190", id_lote = 4, id_quadra = 1 },
  { quadra = "Q34", lote = "L3191", id_lote = 5, id_quadra = 1 },
  { quadra = "Q34", lote = "L3192", id_lote = 6, id_quadra = 1 },
  { quadra = "Q34", lote = "L3193", id_lote = 7, id_quadra = 1 },
  { quadra = "Q34", lote = "L3194", id_lote = 8, id_quadra = 1 },
  { quadra = "Q34", lote = "L3195", id_lote = 9, id_quadra = 1 },
  { quadra = "Q34", lote = "L3196", id_lote = 10, id_quadra = 1 },
  { quadra = "Q34", lote = "L3197", id_lote = 11, id_quadra = 1 },
  { quadra = "Q34", lote = "L3202", id_lote = 12, id_quadra = 1 },
  { quadra = "Q34", lote = "L3203", id_lote = 13, id_quadra = 1 },
  { quadra = "Q34", lote = "L3204", id_lote = 14, id_quadra = 1 },
  { quadra = "Q34", lote = "L3205", id_lote = 15, id_quadra = 1 },
  { quadra = "Q34", lote = "L3206", id_lote = 16, id_quadra = 1 },
  { quadra = "Q34", lote = "L3207", id_lote = 17, id_quadra = 1 },
  { quadra = "Q34", lote = "L3208", id_lote = 18, id_quadra = 1 },
  { quadra = "Q34", lote = "L3209", id_lote = 19, id_quadra = 1 },
  { quadra = "Q34", lote = "L3212", id_lote = 20, id_quadra = 1 },
  { quadra = "Q34", lote = "L3288", id_lote = 21, id_quadra = 1 },
  { quadra = "Q34", lote = "L3289", id_lote = 22, id_quadra = 1 },
  { quadra = "Q34", lote = "L3290", id_lote = 23, id_quadra = 1 },
  { quadra = "Q34", lote = "L3291", id_lote = 24, id_quadra = 1 },
  { quadra = "Q34", lote = "L3292", id_lote = 25, id_quadra = 1 },
  { quadra = "Q34", lote = "L3293", id_lote = 26, id_quadra = 1 },
  { quadra = "Q34", lote = "L3294", id_lote = 27, id_quadra = 1 },
  { quadra = "Q34", lote = "L3295", id_lote = 28, id_quadra = 1 },
  { quadra = "Q34", lote = "L5175", id_lote = 29, id_quadra = 1 },
  { quadra = "Q36", lote = "L3183", id_lote = 0, id_quadra = 2 },
  { quadra = "Q36", lote = "L3213", id_lote = 1, id_quadra = 2 },
  { quadra = "Q36", lote = "L3237", id_lote = 2, id_quadra = 2 },
  { quadra = "Q36", lote = "L3238", id_lote = 3, id_quadra = 2 },
  { quadra = "Q36", lote = "L3239", id_lote = 4, id_quadra = 2 },
  { quadra = "Q36", lote = "L3279", id_lote = 5, id_quadra = 2 },
  { quadra = "Q36", lote = "L3280", id_lote = 6, id_quadra = 2 },
  { quadra = "Q36", lote = "L3282", id_lote = 7, id_quadra = 2 },
  { quadra = "Q36", lote = "L3283", id_lote = 8, id_quadra = 2 },
  { quadra = "Q36", lote = "L3284", id_lote = 9, id_quadra = 2 },
  { quadra = "Q36", lote = "L3285", id_lote = 10, id_quadra = 2 },
  { quadra = "Q36", lote = "L3286", id_lote = 11, id_quadra = 2 },
  { quadra = "Q36", lote = "L3287", id_lote = 12, id_quadra = 2 },
  { quadra = "Q36", lote = "L3296", id_lote = 13, id_quadra = 2 },
  { quadra = "Q36", lote = "L3297", id_lote = 14, id_quadra = 2 },
  { quadra = "Q36", lote = "L3298", id_lote = 15, id_quadra = 2 },
  { quadra = "Q36", lote = "L3299", id_lote = 16, id_quadra = 2 },
  { quadra = "Q36", lote = "L3300", id_lote = 17, id_quadra = 2 },
  { quadra = "Q36", lote = "L3301", id_lote = 18, id_quadra = 2 },
  { quadra = "Q36", lote = "L3302", id_lote = 19, id_quadra = 2 },
  { quadra = "Q36", lote = "L3303", id_lote = 20, id_quadra = 2 },
  { quadra = "Q36", lote = "L3304", id_lote = 21, id_quadra = 2 },
  { quadra = "Q36", lote = "L3305", id_lote = 22, id_quadra = 2 },
  { quadra = "Q36", lote = "L3306", id_lote = 23, id_quadra = 2 },
  { quadra = "Q36", lote = "L3307", id_lote = 24, id_quadra = 2 },
  { quadra = "Q36", lote = "L3308", id_lote = 25, id_quadra = 2 },
  { quadra = "Q36", lote = "L3309", id_lote = 26, id_quadra = 2 },
  { quadra = "Q36", lote = "L3310", id_lote = 27, id_quadra = 2 },
  { quadra = "Q36", lote = "L3311", id_lote = 28, id_quadra = 2 },
  { quadra = "Q36", lote = "L3312", id_lote = 29, id_quadra = 2 },
  { quadra = "Q36", lote = "L3313", id_lote = 30, id_quadra = 2 },
  { quadra = "Q36", lote = "L3314", id_lote = 31, id_quadra = 2 },
  { quadra = "Q36", lote = "L3315", id_lote = 32, id_quadra = 2 },
  { quadra = "Q36", lote = "L3316", id_lote = 33, id_quadra = 2 },
  { quadra = "Q36", lote = "L3317", id_lote = 34, id_quadra = 2 },
  { quadra = "Q36", lote = "L3318", id_lote = 35, id_quadra = 2 },
  { quadra = "Q36", lote = "L3319", id_lote = 36, id_quadra = 2 },
  { quadra = "Q36", lote = "L3320", id_lote = 37, id_quadra = 2 },
  { quadra = "Q36", lote = "L3321", id_lote = 38, id_quadra = 2 },
  { quadra = "Q36", lote = "L3322", id_lote = 39, id_quadra = 2 },
  { quadra = "Q36", lote = "L5178", id_lote = 40, id_quadra = 2 },
  { quadra = "Q36", lote = "L5252", id_lote = 41, id_quadra = 2 },
  { quadra = "Q37", lote = "L3160", id_lote = 0, id_quadra = 3 },
  { quadra = "Q37", lote = "L3161", id_lote = 1, id_quadra = 3 },
  { quadra = "Q37", lote = "L3186", id_lote = 2, id_quadra = 3 },
  { quadra = "Q37", lote = "L3187", id_lote = 3, id_quadra = 3 },
  { quadra = "Q37", lote = "L3188", id_lote = 4, id_quadra = 3 },
  { quadra = "Q37", lote = "L3221", id_lote = 5, id_quadra = 3 },
]
